# rule identifiers to exclude from running
disabled_rules:
  - trailing_whitespace
  - todo

# some rules are only opt-in
opt_in_rules:
  - empty_count
  - force_unwrapping

included:
  - ../Extra

# paths to ignore during linting. Takes precedence over `included`.
excluded:
  - Carthage
  - Pods

line_length:
  warning: 200
  error: 250

variable_name:
  min_length:
    warning: 2
  excluded:
    - preferredInterfaceOrientationForPresentation
    - "ex_*"
