# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

language: objective-c
osx_image: xcode8
before_install:
 - gem install xcpretty -N --no-ri --no-rdoc
 - gem install cocoapods --pre --no-rdoc --no-ri --no-document --quiet
 - pod install --project-directory=Example
script:
- |
  set -o pipefail
  xcodebuild clean test -workspace Example/Extra.xcworkspace -scheme Example/Extra-Example -destination "platform=iOS Simulator,name=iPhone 6 Plus" | xcpretty
#- pod lib lint
